### PR TITLE
moved SAML specific method get_saml_slos to the cas+saml client class

### PR DESCRIPTION
**Pull request by evgenyfadeev**
moved method from one class to another

### CODE REVIEW

**Comment by pipermerriam** [comment]
Can you explain what problem this PR is fixing?

**Comment by evgenyfadeev** [comment]
It is moving a SAML specific method to the class dedicated to handling CAS+SAML protocol from the generic base class.

**Comment by evgenyfadeev** [comment]
@pipermerriam @mingchen could you have a look at this issue please https://github.com/mingchen/django-cas-ng/issues/45

It is related to the file edited by the current PR.

**Comment by mingchen** [comment]
I have added comment on #45 
You can push directly to https://github.com/python-cas/python-cas

> I created a dedicate org name python-cas and invited you as owner. An empty repo python-cas also created, you can feel free to push code to this repo.

**Comment by evgenyfadeev** [comment]
Ok, I will do that later today. Thank you.

**Comment by mingchen** [comment]
My plan is transfer django-cas-ng under python-cas later.

**Comment by evgenyfadeev** [comment]
Meaning the django-independent part under python-cas or together with the
django?

On Tue, Jun 16, 2015 at 2:55 PM, Ming Chen <notifications@github.com> wrote:

> My plan is transfer django-cas-ng under python-cas later.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mingchen/django-cas-ng/pull/47#issuecomment-112513753>
> .
>



-- 
Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by mingchen** [comment]
There will be two repos: python-cas and django-cas-ng. django-cas-ng depend python-cas.

**Comment by evgenyfadeev** [comment]
sounds great!

On Tue, Jun 16, 2015 at 3:00 PM, Ming Chen <notifications@github.com> wrote:

> There will be two repos: python-cas and django-cas-ng. django-cas-ng
> depend python-cas.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mingchen/django-cas-ng/pull/47#issuecomment-112515146>
> .
>



-- 
Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by pipermerriam** [comment]
I love this idea.  Will try to set some time aside to get the python packaging part of `python-cas` setup if nobody objects.

**Comment by evgenyfadeev** [comment]
Piper, sorry I've preempted, made the first commit to
https://github.com/python-cas/python-cas

Please have a look, some links need to be fixed in the README.rst,
also test.py does not run unless the command is:

test.py -p no:django

I wonder if there is a way to fix this.

On Tue, Jun 16, 2015 at 3:40 PM, Piper Merriam <notifications@github.com>
wrote:

> I love this idea. Will try to set some time aside to get the python
> packaging part of python-cas setup if nobody objects.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mingchen/django-cas-ng/pull/47#issuecomment-112524478>
> .
>



-- 
Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Pull request merged**
