### PR TITLE
adds dependency on python-cas

### PR DESCRIPTION
**Pull request by evgenyfadeev**
All test cases and changes in django-cas-ng were ported to python-cas in the repository.

### CODE REVIEW

**Comment by evgenyfadeev** [comment]
In the PR dependency on python-cas is from the github repository, not pypi, i.e. requirements files will need to be edited.

**Comment by mingchen** [comment]
Great.
What's the purpose of not depend on pypi ?

**Comment by evgenyfadeev** [comment]
So that you could test. Also a new release of python-cas would be needed from the github master branch.

**Comment by mingchen** [comment]
I just created a new release of django-cas-ng-3.5.0 and python-cas-1.1.0.

**Comment by evgenyfadeev** [comment]
Awesome, strange thing is that on
https://pypi.python.org/pypi/python-cas/1.1.0
The title says "CAS 1.0/2.0 client authentication backend for Django
(inherited from django-cas)".

On Sun, Nov 8, 2015 at 8:03 PM, Ming Chen <notifications@github.com> wrote:

> I just created a new release of django-cas-ng-3.5.0 and python-cas-1.1.0.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mingchen/django-cas-ng/pull/66#issuecomment-154841198>
> .
>



-- 
Askbot
Valparaiso, Chile
skype: evgeny-fadeev

**Comment by mingchen** [comment]
The text comes from setup.py. I will update it later.

**Pull request merged**
