### PR TITLE
Upgrade to support Django 3.0

### PR DESCRIPTION
**Pull request by ityoung**

### CODE REVIEW

**Comment by ityoung** [comment]
bumped version to 4.0.0

**Comment by ityoung** [comment]
really need this, please contact me if more update needed.

**Comment by ityoung** [comment]
#223

**Comment by intgr** [comment]
I'm interested in this as well. Hoping for a release soon? :)

**Comment by AmShaegar13** [comment]
Thank you! @mingchen @ityoung

**Comment by intgr** [comment]
Thanks @mingchen, your continued maintenance of this project is much appreciated.

**Pull request merged**
